#ifndef _RANDOM_FIELD_H
#define _RANDOM_FIELD_H

#include "rgb.h"



#define RANDOM_FIELD_WIDTH 24
#define RANDOM_FIELD_HEIGHT RANDOM_FIELD_WIDTH

extern const struct Rgb RANDOM_FIELD[RANDOM_FIELD_WIDTH][RANDOM_FIELD_HEIGHT];



#endif//_RANDOM_FIELD_H